config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :categories
  resources :comments, only: [:create]
  resources :users, except: [:new]

  # Stories
  resources :stories
  get 'subscribed', to: 'stories#subscribed', as: 'subscribed'
  delete '/comments/:id', to: 'comments#destroy', as: 'delete_comment'

  # Static pages
  root 'pages#home'

  ## Session
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  ## Follow feature
  post '/users/:id/follow', to: 'users#follow', as: 'follow_user'
  post '/users/:id/unfollow', to: 'users#unfollow', as: 'unfollow_user'
  get '/users/:id/follower', to: 'users#follower', as: 'follower'
  get '/users/:id/following', to: 'users#following', as: 'following'
  
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :stories, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow', dependent: :destroy
    has_many :followings, through: :followed_users
    has_many :following_users, foreign_key: :following_id, class_name: 'Follow', dependent: :destroy
    has_many :followers, through: :following_users

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :username, presence: true, 
        uniqueness: { case_sensitive: false }, 
        length: { minimum: 3, maximum: 25 }
    validates :email, presence: true, 
        uniqueness: { case_sensitive: false }, 
        length: { maximum: 126 },
        format: { with: VALID_EMAIL_REGEX, message: "format incorrect" }
    has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :get_user, only: [:show, :edit, :update, :destroy, :follow, :unfollow, :follower, :following]
    before_action :require_user, only: [:edit, :update, :destroy, :follow, :unfollow]
    before_action :is_owner, only: [:edit, :update, :destroy, :follower, :following]

    def follow
        current_user.followings << @user
        redirect_to @user
    end
    
    def unfollow
        current_user.followed_users.find_by(following_id: @user.id).destroy
        redirect_to @user
    end

    def follower
        @users = @user.followers.paginate(page: params[:page], per_page: 6).order(created_at: :desc)
    end

    def following
        @users = @user.followings.paginate(page: params[:page], per_page: 6).order(created_at: :desc)
    end

    def index
        if params[:search]
            @users = User.where("lower(username) LIKE ?", "%#{params[:search].downcase}%").paginate(page: params[:page], per_page: 6).order(created_at: :desc)
        else
            @users = User.paginate(page: params[:page], per_page: 6).order(created_at: :desc)
        end
    end

    def show
        if params[:search]
            @stories = @user.stories.where("lower(title) LIKE ?", "%#{params[:search].downcase}%").paginate(page: params[:page], per_page: 5).order(created_at: :desc)
        else
            @stories = @user.stories.paginate(page: params[:page], per_page: 5).order(created_at: :desc)
        end
    end

    def new
        @user = User.new
    end

    def edit
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "Welcome #{@user.username}, you have successfully signup."
            redirect_to @user
        else
            render 'new'
        end
    end

    def update 
        if @user.update(user_params)
            flash[:notice] = "Account information was updated successfully."
            redirect_to @user
        else
            render 'edit'
        end
    end

    def destroy 
        @user.destroy
        session[:user_id] = nil if current_user == @user
        flash[:notice] = "The account and associated story deleted successfully"
        redirect_to root_path
    end

    private
    def get_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def is_owner
        if current_user != @user && !current_user.is_admin?
            flash[:alert] = "You only can modify your own account" 
            redirect_to @user
        end
    end

end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>
    <div class="form-group">
        <%= form.label :username %>
        <%= form.text_field :username, placeholder: 'Type your username here', class: "form-control" %>
    </div>
    <div class="form-group">
        <%= form.label :email %>
        <%= form.email_field :email, placeholder: 'Type your email here', class: "form-control" %>
        <small class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
        <%= form.label :password %>
        <%= form.password_field :password, placeholder: 'Type your password here', class: "form-control" %>
    </div>
    <%= render 'shared/error', obj: @user %>
    <div class="text-right">
        <% if !@user.new_record? %>
            <%= link_to "Delete Account", user_path(current_user), method: :delete, 
                data: { confirm: "Are you sure you want to delete your profile?" },
                class:"btn btn-danger" %>
        <% end %>
        <%= form.submit(@user.new_record? ? "Sign up" : "Update Account", class: "btn btn-primary") %>
    </div>
<% end %>

app/views/users/_users.html.erb
<div class="card-deck d-flex justify-content-md-center">
    <% if !obj.any? %>
        <div class="card text-center mt-3 bg-light">
            <div class="card-body">No user found.</div>
        </div>
    <% end %>
    <% obj.each do |user| %>
    <div class="card mt-3 text-center" style="min-width: 29%; max-width: 30%">
        <%= link_to gravatar_for(user, size: 100), user, class: "card-img-top mt-3", alt: "user.username" %>
        <div class="card-body">
            <%= link_to user.username, user, class: "card-title" %>
            <div class="card-text"><%= pluralize(user.stories.count, "story") %></div>
            <div class="btn-group mt-3">
                <%= link_to 'View', user, class: "btn btn-outline-primary" %>
                <% if logged_in? %>
                    <% if user == current_user %>
                        <%= link_to 'Edit', edit_user_path(user.id), class:"btn btn-outline-secondary" %>
                    <% else %>
                        <% if current_user.followings.include? user %>
                            <%= link_to 'Unfollow', unfollow_user_path(user.id), method: 'POST', class:"btn btn-outline-secondary" %>
                        <% else %>
                            <%= link_to 'Follow', follow_user_path(user.id), method: 'POST', class:"btn btn-outline-info" %>
                        <% end %>
                        <% if current_user.is_admin %>
                            <%= link_to 'Delete', user_path(user.id), method: :delete, 
                                data: { confirm: "Are you sure you want to delete '#{user.username}' account and it's associated story?" },
                                class:"btn btn-outline-danger" %>
                        <% end %>
                    <% end %>
                <% end %>
            </div>
        </div>
        <div class="card-footer">
            <small class="text-muted">Joined <%= time_ago_in_words(user.created_at) %> ago</small>
        </div>
    </div>
    <% end %>
</div>

app/views/users/edit.html.erb
<div class="card">
    <div class="card-body">
        <h1 class="text-center mt-4 card-title">Edit account</h1>
        <%= render 'form' %>
    </div>
    <%= render 'shared/return_home_footer', obj: nil %>
</div>

app/views/users/follower.html.erb
<div class="card">
    <div class="card-header">
        <h2 class="text-center">Follower</h2>
    </div>
    <div class="card-body">
        <%= render 'users', obj: @users %>
        <div class="flickr_pagination mt-3">
            <%= will_paginate @stories, :container => false %>
        </div>
    </div>
    <%= render 'shared/return_home_footer', obj: nil %>
</div>

app/views/users/following.html.erb
<div class="card">
    <div class="card-header">
        <h2 class="text-center">Following</h2>
    </div>
    <div class="card-body">
        <%= render 'users', obj: @users %>
        <div class="flickr_pagination mt-3">
            <%= will_paginate @stories, :container => false %>
        </div>
    </div>
    <%= render 'shared/return_home_footer', obj: nil %>
</div>

app/views/users/index.html.erb
<div class="card">
    <div class="card-header">
        <h2 class="text-center">Fabulapad writers</h2>
    </div>
    <div class="card-body">
        <%= render 'shared/search_bar', path: users_path %>
        <%= render 'users', obj: @users %>
        <div class="flickr_pagination mt-3">
            <%= will_paginate @users, :container => false %>
        </div>
    </div>
    <%= render 'shared/return_home_footer', obj: nil %>
</div>

app/views/users/new.html.erb
<div class="card">
    <div class="card-body">
        <h1 class="text-center mt-4 card-title">Signup</h1>
        <%= render 'form' %>
    </div>
    <%= render 'shared/return_home_footer', obj: nil %>
</div>

app/views/users/show.html.erb
<div class="card">
    <div class="card-body">
        <h1 class="text-center mt-4 card-title"><%= @user.username %>'s Story</h1>
        <div class="mb-4">
            <%= gravatar_for @user, size: 150 %>
        </div>
        <% if logged_in? %>
            <div class="mb-3 text-center">
                <div class="btn-group">
                    <% if @user == current_user %>
                        <%= link_to 'Follower', follower_path(@user), class:"btn btn-outline-info" %>
                        <%= link_to 'Edit account', edit_user_path(@user), class:"btn btn-outline-success" %>
                        <%= link_to 'Following', following_path(@user), class:"btn btn-outline-info" %>
                    <% elsif current_user.followings.include? @user %>
                        <%= link_to 'Unfollow', unfollow_user_path(@user.id), method: 'POST', class:"btn btn-outline-secondary" %>
                    <% else %>
                        <%= link_to 'Follow', follow_user_path(@user.id), method: 'POST', class:"btn btn-outline-info" %>
                    <% end %>
                </div>
            </div>
        <% end %>
        <%= render 'shared/search_bar', path: user_path(@user) %>
        <%= render 'stories/stories', obj: @stories %>
        <div class="flickr_pagination mt-3">
            <%= will_paginate @stories, :container => false %>
        </div>
    </div>
    <%= render 'shared/return_home_footer', obj: nil %>
</div>