config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :categories
  resources :comments, only: [:create]
  resources :users, except: [:new]

  # Stories
  resources :stories
  get 'subscribed', to: 'stories#subscribed', as: 'subscribed'
  delete '/comments/:id', to: 'comments#destroy', as: 'delete_comment'

  # Static pages
  root 'pages#home'

  ## Session
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  ## Follow feature
  post '/users/:id/follow', to: 'users#follow', as: 'follow_user'
  post '/users/:id/unfollow', to: 'users#unfollow', as: 'unfollow_user'
  get '/users/:id/follower', to: 'users#follower', as: 'follower'
  get '/users/:id/following', to: 'users#following', as: 'following'
  
end

app/models/story.rb
class Story < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :story_categories, dependent: :destroy
    has_many :categories, through: :story_categories
    scope :subscribed, ->(followers) { where user_id: followers }

    validates :title, presence: true, length: { minimum: 6, maximum: 255 }
    validates :content, presence: true, length: { minimum: 50, message: "length are to short" }
    has_rich_text :content
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
    before_action :get_story, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :is_owner, only: [:edit, :update, :destroy]

    def subscribed
        if params[:search]
            @stories = Story.subscribed(current_user.followings).where("lower(title) LIKE ?", "%#{params[:search].downcase}%").paginate(page: params[:page], per_page: 7).order(created_at: :desc)
        else
            @stories = Story.subscribed(current_user.followings).paginate(page: params[:page], per_page: 7).order(created_at: :desc)
        end
    end

    def show
        @comments = @story.comments.paginate(page: params[:page], per_page: 5).order(created_at: :desc)
        @comment = Comment.new
    end

    def index
        if params[:search]
            @stories = Story.where("lower(title) LIKE ?", "%#{params[:search].downcase}%").paginate(page: params[:page], per_page: 7).order(created_at: :desc)
        else
            @stories = Story.paginate(page: params[:page], per_page: 7).order(created_at: :desc)
        end
    end

    def new
        @story = Story.new
    end

    def edit
    end

    def create
        @story = Story.new(story_params)
        @story.user = current_user
        if @story.save
            flash[:notice] = "Story was saved successfully."
            redirect_to @story
        else
            render 'new'
        end
    end 

    def update
        if @story.update(story_params)
            flash[:notice] = "Story was updated successfully."
            redirect_to @story
        else
            render 'edit'
        end
    end

    def destroy
        @story.destroy
        redirect_to stories_path
    end 

    private 
    def get_story
        @story = Story.find(params[:id])
    end

    def story_params
        params.require(:story).permit(:title, :content, category_ids: [])
    end

    def is_owner
        if current_user != @story.user && !current_user.is_admin?
            flash[:alert] = "Access only accessible by the owner" 
            redirect_to stories_path
        end
    end

end

app/views/stories/_comments_section.html.erb
<div class="card mt-5">
    <div class="card-body">
        <h5 class="font-weight-bold">Comments</h5>
        <hr />
        <% obj.each do |comment| %>
            <div class="mx-3 row  <%= "justify-content-end" if logged_in? && comment.user == current_user %>">
                <div class="card mb-3 w-75 <%= "text-right" if logged_in? && comment.user == current_user %>">
                    <div class="card-header d-flex w-100 justify-content-between">
                        <% if logged_in? && comment.user == current_user %>
                            <%= link_to 'remove', delete_comment_path(comment.id), method: :delete, data: { confirm: "Are you sure you ?" }, class:"badge badge-pill badge-danger ml-1" %>
                            <small class="text-muted">
                                    You <%= time_ago_in_words(comment.created_at) %> ago
                            </small>
                        <% else %>
                            <small class="text-muted">
                                    <%= link_to comment.user.username, user_path(comment.user) %> <%= time_ago_in_words(comment.created_at) %> ago
                            </small>
                            <% if logged_in? && current_user.is_admin? %>
                            <%= link_to 'remove', delete_comment_path(comment.id), method: :delete, data: { confirm: "Are you sure you ?" }, class:"badge badge-pill badge-danger ml-1" %>
                            <% end %>
                        <% end %> 
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><%= comment.content %></li>
                    </ul>
                </div>
            </div>
        <% end %>
        <div class="flickr_pagination mt-3">
            <%= will_paginate obj, :container => false %>
        </div>
        <% if logged_in? %>
            <%= form_with(model: @comment, local: true) do |form| %>
                <%= form.hidden_field :user_id, :value => current_user.id %>
                <%= form.hidden_field :story_id, :value => @story.id %>
                <div class="form-group">
                    <%= form.label 'Add comment content' %>
                    <%= form.text_area :content, placeholder: 'Type your comment content here', class: "form-control" %>
                </div>
                <div class="text-right">
                    <%= form.submit 'Submit', class: "btn btn-primary" %>
                </div>
            <% end %>
        <% else %>
            <div class="card text-center mt-3 bg-light">
                <div class="card-body">Please login to comment.</div>
            </div>
        <% end %>
    </div>
</div>

app/views/stories/_form.html.erb
<%= form_with(model: @story, local: true) do |form| %>
    <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, placeholder: 'Type your title here', class: "form-control" %>
    </div>
    <div class="form-group field">
        <%= form.label :category %>
        <%= form.collection_select :category_ids , Category.order(:name), :id, :name, { promt: "Select all the matching category (can be empty)" }, { multiple: true, size: 5, class: "custom-select form-control" } %>
    </div>
    <div class="form-group field">
        <%= form.label :content %>
        <%= form.rich_text_area :content, placeholder: 'Type your story here' %>
    </div>
    <%= render 'shared/error', obj: @story %>
    <div class="text-right">
        <%= form.submit class: "btn btn-primary" %>
    </div>
<% end %>

app/views/stories/_stories.html.erb
<div class="list-group list-group-flush">
    <% if !obj.any? %>
        <div class="card text-center mt-3">
            <div class="card-body">No story found.</div>
        </div>
    <% end %>
    <% obj.each do |story| %>
    <div href="#" class="list-group-item list-group-item-action flex-column align-items-start mt-3">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1 font-weight-bold"><%= link_to story.title, story_path(story), class:"text-primary" %></h5>
            <small>by <%= link_to story.user.username, user_path(story.user) %> - Created <%= time_ago_in_words(story.created_at) %> ago</small>
        </div>
        <p class="mb-1 font-weight-light"><%= truncate(story.content.to_plain_text, :length => 120) %></p>
        <div class="d-flex justify-content-between align-self-center">
            <small>
                <% if story.categories.any? %>
                    <%= render story.categories %>
                <% end %>
            </small>
            <div class="btn-group">
                <%= link_to 'View', story_path(story.id), class: "badge btn btn-outline-success" %>
                <% if logged_in? && (story.user == current_user || current_user.is_admin?) %>
                    <%= link_to 'Edit', edit_story_path(story.id), class:"badge btn btn-outline-secondary" %>
                    <%= link_to 'Delete', story_path(story.id), method: :delete, data: { confirm: 'Are you sure?' }, class:"badge btn btn-outline-danger" %>
                <% end %>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/stories/edit.html.erb
<div class="card">
    <div class="card-body">
        <h1 class="text-center mt-4 card-title">Edit an existing story</h1>
        <%= render 'form' %>
    </div>
    <%= render 'shared/return_home_footer', obj: @story %>
</div>

app/views/stories/index.html.erb
<div class="card">
    <div class="card-header">
        <h2 class="text-center">Stories</h2>
    </div>
    <div class="card-body">
        <%= render 'shared/search_bar', path: stories_path %>
        <%= render 'stories', obj: @stories %>
        <div class="flickr_pagination mt-3">
            <%= will_paginate @stories, :container => false %>
        </div>
        <% if logged_in? %>
            <%= link_to 'Create a new story', new_story_path, class: "btn btn-primary btn-lg btn-block mt-3" %>
        <% end %>
    </div>
    <%= render 'shared/return_home_footer', obj: nil %>
</div>

app/views/stories/new.html.erb
<div class="card">
    <div class="card-body">
        <h1 class="text-center mt-4 card-title">Create a new Story</h1>
        <%= render 'form' %>
    </div>
    <%= render 'shared/return_home_footer', obj: nil %>
</div>

app/views/stories/show.html.erb
<div class="card">
    <div class="card-header">
        <h2 class="text-center"><%= @story.title %></h2>
    </div>
    <div class="card-body">
        <div class="text-center card-title">
            <h5 >by <%= link_to @story.user.username, user_path(@story.user) %></h5>
            <% if @story.categories.any? %>
                <%= render @story.categories %>
            <% end %>
        </div>
        <div class="trix-content card-text text-justify">
            <%= @story.content %>
        </div>
        <% if logged_in? && (@story.user == current_user || current_user.is_admin?) %>
        <div class="text-center mt-3">
            <div class="btn-group">
                <%= link_to 'Edit', edit_story_path(@story.id), class:"btn btn-outline-secondary" %>
                <%= link_to 'Delete', story_path(@story.id), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger" %>
            </div>
        </div>
        <% end %>
    </div>
    <%= render 'shared/return_home_footer', obj: nil %>
</div>
<%= render 'comments_section', obj: @comments %>

app/views/stories/subscribed.html.erb
<div class="card">
    <div class="card-header">
        <h2 class="text-center">Subscribed writer stories</h2>
    </div>
    <div class="card-body">
        <%= render 'shared/search_bar', path: subscribed_path %>
        <%= render 'stories', obj: @stories %>
        <div class="flickr_pagination mt-3">
            <%= will_paginate @stories, :container => false %>
        </div>
    </div>
    <%= render 'shared/return_home_footer', obj: nil %>
</div>