config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :categories
  resources :comments, only: [:create]
  resources :users, except: [:new]

  # Stories
  resources :stories
  get 'subscribed', to: 'stories#subscribed', as: 'subscribed'
  delete '/comments/:id', to: 'comments#destroy', as: 'delete_comment'

  # Static pages
  root 'pages#home'

  ## Session
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  ## Follow feature
  post '/users/:id/follow', to: 'users#follow', as: 'follow_user'
  post '/users/:id/unfollow', to: 'users#unfollow', as: 'unfollow_user'
  get '/users/:id/follower', to: 'users#follower', as: 'follower'
  get '/users/:id/following', to: 'users#following', as: 'following'
  
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :story_categories, dependent: :destroy
    has_many :stories, through: :story_categories

    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :get_category, only: [:show, :edit, :update, :destroy]
    before_action :require_admin, except: [:index, :show]

    def index
        if params[:search]
            @category = Category.where("lower(name) LIKE ?", "%#{params[:search].downcase}%").paginate(page: params[:page], per_page: 6).order(created_at: :desc)
        else
            @category = Category.paginate(page: params[:page], per_page: 6).order(created_at: :desc)
        end
    end

    def show
        if params[:search]
            @stories = @category.stories.where("lower(title) LIKE ?", "%#{params[:search].downcase}%").paginate(page: params[:page], per_page: 5).order(created_at: :desc)
        else
            @stories = @category.stories.paginate(page: params[:page], per_page: 5).order(created_at: :desc)
        end
    end
    
    def new
        @category = Category.new
    end

    def edit
    end

    def create
        @category = Category.new(category_params)
        @category.name = @category.name.downcase if @category.valid?
        if @category.save
            flash[:notice] = "New category added successfully"
            redirect_to @category
        else
            render 'new'
        end
    end

    def update
        if @category.update(category_params)
            flash[:notice] = "Category was renamed successfully."
            redirect_to @category
        else
            render 'edit'
        end
    end

    def destroy
        @category.destroy
        redirect_to categories_path
    end 

    private
    def get_category
        @category = Category.find(params[:id])
    end

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.is_admin?)
            flash[:alert] = "Only admin can perform that action"
            redirect_to categories_path
        end
    end

end

app/views/categories/_categories.html.erb
<div class="row d-flex justify-content-md-center">
    <% if !obj.any? %>
    <div class="col-12 mt-3">
        <div class="card text-center mt-3 bg-light">
            <div class="card-body">No category found.</div>
        </div>
    </div>
    <% end %>
    <% obj.each do |category| %>
    <div class="col-4 mt-3">
        <div class="card text-center">
            <div class="card-header">
                <small class="text-muted">Created <%= time_ago_in_words(category.created_at) %> ago</small>
            </div>
            <div class="card-body">
                <h5 class="card-title"><%= link_to category.name.capitalize, category_path(category), class: "text-decoration-none" %></h5>
                <p class="card-text"><%= pluralize(category.stories.count, "story") %></p>
            </div>
            <div class="btn-group mt-1 mb-1 card-footer">
                <%= link_to 'View', category_path(category.id), class: "btn btn-outline-success" %>
                <% if logged_in? && current_user.is_admin %>
                    <%= link_to 'Edit', edit_category_path(category.id), class:"btn btn-outline-secondary" %>
                    <%= link_to 'Delete', category_path(category.id), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger" %>
                <% end %>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name.capitalize, category_path(category), class: "badge rounded-pill badge-success mr-2" %>

app/views/categories/_form.html.erb
<%= form_with(model: @category, local: true) do |form| %>
    <div class="input-group mb-2 mt-5">
        <div class="input-group-prepend">
            <%= form.label :name, "Category name", class: "input-group-text" %>
        </div>
        <%= form.text_field :name, placeholder: 'Type the category name here', class: "form-control" %>
    </div>
    <%= render 'shared/error', obj: @category %>
    <div class="text-right">
        <%= form.submit(@category.new_record? ? "Add Category" : "Rename Category", class: "btn btn-primary") %>
    </div>
<% end %>

app/views/categories/edit.html.erb
<div class="card">
    <div class="card-body">
        <h1 class="text-center mt-4 card-title">Rename category</h1>
        <%= render 'form' %>
    </div>
    <%= render 'shared/return_home_footer', obj: nil %>
</div>

app/views/categories/index.html.erb
<div class="card">
    <div class="card-body">
        <h1 class="text-center mt-4 card-title">Categories</h1>
        <%= render 'shared/search_bar', path: categories_path %>
        <%= render 'categories', obj: @category %>
        <div class="flickr_pagination mt-3">
            <%= will_paginate @category, :container => false %>
        </div>
        <% if logged_in? && current_user.is_admin %>
            <%= link_to 'Add a new category', new_category_path, class: "btn btn-primary btn-lg btn-block mt-3" %>
        <% end %>
    </div>
    <%= render 'shared/return_home_footer', obj: nil %>
</div>

app/views/categories/new.html.erb
<div class="card">
    <div class="card-body">
        <h1 class="text-center mt-4 card-title">Add a new category</h1>
        <%= render 'form' %>
    </div>
    <%= render 'shared/return_home_footer', obj: nil %>
</div>

app/views/categories/show.html.erb
<div class="card">
    <div class="card-body">
        <h1 class="text-center mt-4 card-title">Category: <%= @category.name.capitalize %></h1>
        <%= render 'shared/search_bar', path: category_path(@category) %>
        <%= render 'stories/stories', obj: @stories %>
        <div class="flickr_pagination mt-3">
            <%= will_paginate @stories, :container => false %>
        </div>
    </div>
    <%= render 'shared/return_home_footer', obj: nil %>
</div>