config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :categories
  resources :comments, only: [:create]
  resources :users, except: [:new]

  # Stories
  resources :stories
  get 'subscribed', to: 'stories#subscribed', as: 'subscribed'
  delete '/comments/:id', to: 'comments#destroy', as: 'delete_comment'

  # Static pages
  root 'pages#home'

  ## Session
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  ## Follow feature
  post '/users/:id/follow', to: 'users#follow', as: 'follow_user'
  post '/users/:id/unfollow', to: 'users#unfollow', as: 'unfollow_user'
  get '/users/:id/follower', to: 'users#follower', as: 'follower'
  get '/users/:id/following', to: 'users#following', as: 'following'
  
end

app/views/layouts/_footer.html.erb
<footer class="sticky-footer py-4 bg-dark text-white">
    <div class="container text-center">
        <small><%= link_to "Copyright© Wendy", "https://www.wendiciadi.com/", class:"text-white", style: "text-decoration: none;" %></small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |key, message| %>
    <div class="alert <%= key == "notice" ? "alert-success" : "alert-warning" %> alert-dismissible fade show" role="alert">
        <%= message %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "Fabulapad", root_path, class:"navbar-brand logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <%= link_to "Categories", categories_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Stories", stories_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Writers", users_path, class:"nav-link" %>
            </li>
            <% if logged_in? %>
                <li class="nav-item">
                    <%= link_to "Subscribed", subscribed_path, class:"nav-link" %>
                </li>   
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
                        <%= current_user.username %>
                        <%= " (admin)" if current_user.is_admin? %>
                    </a>
                    <div class="dropdown-menu">
                        <%= link_to 'My account', user_path(current_user) , class:"dropdown-item" %>
                        <%= link_to 'Edit account', edit_user_path(current_user), class:"dropdown-item" %>
                        <%= link_to 'Follower', follower_path(current_user), class:"dropdown-item" %>
                        <%= link_to 'Following', following_path(current_user), class:"dropdown-item" %>
                    </div>
                </li>
            <% end %>
        </ul>
        <div class="btn-group my-2 my-lg-0">
            <% if logged_in? %>
                <%= link_to "Logout", logout_path, method: :delete, class:"btn btn-success" %>
            <% else %>
                <%= link_to "Signup", signup_path, class: "btn btn-success" %>
                <%= link_to "Login", login_path, class:"btn btn-secondary" %>
            <% end %>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fabulapad</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container padded-container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>